// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aspnetserver.Data;

#nullable disable

namespace aspnetserver.Data.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20221202094352_FirstMigrationForum")]
    partial class FirstMigrationForum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("aspnetserver.Data.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("PostId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            Body = "<Body content 1>",
                            Category = "<Category of the post 1>",
                            Image = "<Image link 1>",
                            Title = "<Title 1>"
                        },
                        new
                        {
                            PostId = 2,
                            Body = "<Body content 2>",
                            Category = "<Category of the post 2>",
                            Image = "<Image link 2>",
                            Title = "<Title 2>"
                        },
                        new
                        {
                            PostId = 3,
                            Body = "<Body content 3>",
                            Category = "<Category of the post 3>",
                            Image = "<Image link 3>",
                            Title = "<Title 3>"
                        },
                        new
                        {
                            PostId = 4,
                            Body = "<Body content 4>",
                            Category = "<Category of the post 4>",
                            Image = "<Image link 4>",
                            Title = "<Title 4>"
                        },
                        new
                        {
                            PostId = 5,
                            Body = "<Body content 5>",
                            Category = "<Category of the post 5>",
                            Image = "<Image link 5>",
                            Title = "<Title 5>"
                        },
                        new
                        {
                            PostId = 6,
                            Body = "<Body content 6>",
                            Category = "<Category of the post 6>",
                            Image = "<Image link 6>",
                            Title = "<Title 6>"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
