// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aspnetserver.Data;

#nullable disable

namespace aspnetserver.Data.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20221129143004_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("aspnetserver.Data.Post", b =>
                {
                    b.Property<int>("FlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AirLineName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ArrivalDay")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ArrivalHour")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DepartureDay")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DepartureHour")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Luggage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Scales")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("FlightId");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            FlightId = 1,
                            AirLineName = "Airline no. 1",
                            ArrivalDay = "<Arrival day for flight no. 1>",
                            ArrivalHour = "<Arrival hour for flight no. 1>",
                            DepartureDay = "<Departure day for flight no. 1>",
                            DepartureHour = "<Departure hour for flight no. 1>",
                            Destination = "Destination city 1",
                            Luggage = "<Luggage for flight no. 1>",
                            Origin = "Origin city 1",
                            Scales = "<Scales for flight no. 1>"
                        },
                        new
                        {
                            FlightId = 2,
                            AirLineName = "Airline no. 2",
                            ArrivalDay = "<Arrival day for flight no. 2>",
                            ArrivalHour = "<Arrival hour for flight no. 2>",
                            DepartureDay = "<Departure day for flight no. 2>",
                            DepartureHour = "<Departure hour for flight no. 2>",
                            Destination = "Destination city 2",
                            Luggage = "<Luggage for flight no. 2>",
                            Origin = "Origin city 2",
                            Scales = "<Scales for flight no. 2>"
                        },
                        new
                        {
                            FlightId = 3,
                            AirLineName = "Airline no. 3",
                            ArrivalDay = "<Arrival day for flight no. 3>",
                            ArrivalHour = "<Arrival hour for flight no. 3>",
                            DepartureDay = "<Departure day for flight no. 3>",
                            DepartureHour = "<Departure hour for flight no. 3>",
                            Destination = "Destination city 3",
                            Luggage = "<Luggage for flight no. 3>",
                            Origin = "Origin city 3",
                            Scales = "<Scales for flight no. 3>"
                        },
                        new
                        {
                            FlightId = 4,
                            AirLineName = "Airline no. 4",
                            ArrivalDay = "<Arrival day for flight no. 4>",
                            ArrivalHour = "<Arrival hour for flight no. 4>",
                            DepartureDay = "<Departure day for flight no. 4>",
                            DepartureHour = "<Departure hour for flight no. 4>",
                            Destination = "Destination city 4",
                            Luggage = "<Luggage for flight no. 4>",
                            Origin = "Origin city 4",
                            Scales = "<Scales for flight no. 4>"
                        },
                        new
                        {
                            FlightId = 5,
                            AirLineName = "Airline no. 5",
                            ArrivalDay = "<Arrival day for flight no. 5>",
                            ArrivalHour = "<Arrival hour for flight no. 5>",
                            DepartureDay = "<Departure day for flight no. 5>",
                            DepartureHour = "<Departure hour for flight no. 5>",
                            Destination = "Destination city 5",
                            Luggage = "<Luggage for flight no. 5>",
                            Origin = "Origin city 5",
                            Scales = "<Scales for flight no. 5>"
                        },
                        new
                        {
                            FlightId = 6,
                            AirLineName = "Airline no. 6",
                            ArrivalDay = "<Arrival day for flight no. 6>",
                            ArrivalHour = "<Arrival hour for flight no. 6>",
                            DepartureDay = "<Departure day for flight no. 6>",
                            DepartureHour = "<Departure hour for flight no. 6>",
                            Destination = "Destination city 6",
                            Luggage = "<Luggage for flight no. 6>",
                            Origin = "Origin city 6",
                            Scales = "<Scales for flight no. 6>"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
